package main.java.com.taskmanager.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import main.java.com.taskmanager.entities.Board;
import main.java.com.taskmanager.repositories.BoardRepository;

import org.springframework.web.bind.annotation.PostMapping;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/board") // This means URL's start with /demo (after Application path)
public class BoardController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private BoardRepository boardRepository;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewBoard(@RequestParam String fname, @RequestParam String lname,
			@RequestParam String email, @RequestParam String password, @RequestParam String repassword) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Board n = new Board();

		/*
		 * Validator validator = Validation.byProvider( HibernateValidator.class )
		 * .configure() .failFast( true ) .buildValidatorFactory() .getValidator();
		 * 
		 * message = validator.validateProperty( car, "licensePlate" ) .iterator()
		 * .next() .getMessage();
		 */

		boardRepository.save(n);
		return "Saved";
	}

}
